this.gbar_=this.gbar_||{};(function(_){var window=this;
try{
var yj;_.xj=function(a){this.b=a||{cookie:""}};_.k=_.xj.prototype;_.k.set=function(a,c,d,e,f,g){if(/[;=\s]/.test(a))throw Error("P`"+a);if(/[;\r\n]/.test(c))throw Error("Q`"+c);_.ua(d)||(d=-1);f=f?";domain="+f:"";e=e?";path="+e:"";g=g?";secure":"";d=0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.Ea)()+1E3*d)).toUTCString();this.b.cookie=a+"="+c+f+e+d+g};
_.k.get=function(a,c){for(var d=a+"=",e=(this.b.cookie||"").split(";"),f=0,g;f<e.length;f++){g=(0,_.Na)(e[f]);if(0==g.lastIndexOf(d,0))return g.substr(d.length);if(g==a)return""}return c};_.k.remove=function(a,c,d){var e=_.ua(this.get(a));this.set(a,"",0,c,d);return e};_.k.lb=function(){return yj(this).keys};_.k.Ta=function(){return yj(this).values};_.k.vc=function(){return!this.b.cookie};_.k.clear=function(){for(var a=yj(this).keys,c=a.length-1;0<=c;c--)this.remove(a[c])};
yj=function(a){a=(a.b.cookie||"").split(";");for(var c=[],d=[],e,f,g=0;g<a.length;g++)f=(0,_.Na)(a[g]),e=f.indexOf("="),-1==e?(c.push(""),d.push(f)):(c.push(f.substring(0,e)),d.push(f.substring(e+1)));return{keys:c,values:d}};_.zj=new _.xj("undefined"==typeof window.document?null:window.document);_.zj.f=3950;

}catch(e){_._DumpException(e)}
try{
_.Aj=function(a,c,d){a.b||(a.b={});var e=d?d.Vb():d;a.b[c]=d;_.D(a,c,e)};_.Bj={};_.Cj=function(a,c){_.Bj[a]=c;c.tk=a};_.Dj=function(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};_.Ej=function(){};_.Ej.prototype.f=null;var Gj;Gj=function(){};_.v(Gj,_.Ej);Gj.prototype.b=function(){var a=Hj(this);return a?new window.ActiveXObject(a):new window.XMLHttpRequest};Gj.prototype.o=function(){var a={};Hj(this)&&(a[0]=!0,a[1]=!0);return a};
var Hj=function(a){if(!a.j&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0;d<c.length;d++){var e=c[d];try{return new window.ActiveXObject(e),a.j=e}catch(f){}}throw Error("R");}return a.j};_.Fj=new Gj;

}catch(e){_._DumpException(e)}
try{
_.Ij=function(a){return a instanceof _.id&&a.constructor===_.id&&a.f===_.hd?a.b:"type_error:Const"};_.Jj=function(a){return _.qd(_.Ij(a))};_.Kj=function(a){return a?_.Gd(a):window};_.Lj=function(a){return a.contentDocument||a.contentWindow.document};_.Mj=function(a,c){this.f={};this.b=[];this.j=0;var d=arguments.length;if(1<d){if(d%2)throw Error("c");for(var e=0;e<d;e+=2)this.set(arguments[e],arguments[e+1])}else if(a)if(a instanceof _.Mj)for(d=a.lb(),e=0;e<d.length;e++)this.set(d[e],a.get(d[e]));else for(e in a)this.set(e,a[e])};_.Mj.prototype.Ta=function(){Nj(this);for(var a=[],c=0;c<this.b.length;c++)a.push(this.f[this.b[c]]);return a};_.Mj.prototype.lb=function(){Nj(this);return this.b.concat()};_.Pj=function(a,c){return Oj(a.f,c)};
_.Mj.prototype.vc=function(){return 0==this.j};_.Mj.prototype.clear=function(){this.f={};this.j=this.b.length=0};_.Mj.prototype.remove=function(a){return Oj(this.f,a)?(delete this.f[a],this.j--,this.b.length>2*this.j&&Nj(this),!0):!1};var Nj=function(a){if(a.j!=a.b.length){for(var c=0,d=0;c<a.b.length;){var e=a.b[c];Oj(a.f,e)&&(a.b[d++]=e);c++}a.b.length=d}if(a.j!=a.b.length){var f={};for(d=c=0;c<a.b.length;)e=a.b[c],Oj(f,e)||(a.b[d++]=e,f[e]=1),c++;a.b.length=d}};
_.Mj.prototype.get=function(a,c){return Oj(this.f,a)?this.f[a]:c};_.Mj.prototype.set=function(a,c){Oj(this.f,a)||(this.j++,this.b.push(a));this.f[a]=c};_.Mj.prototype.forEach=function(a,c){for(var d=this.lb(),e=0;e<d.length;e++){var f=d[e],g=this.get(f);a.call(c,g,f,this)}};var Oj=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};
var Qj;Qj=function(a){return(a=a.exec(_.Qa))?a[1]:""};_.Rj=function(){if(_.Cb)return Qj(/Firefox\/([0-9.]+)/);if(_.y||_.eb||_.db)return _.vb;if(_.Gb)return _.$a()?Qj(/CriOS\/([0-9.]+)/):Qj(/Chrome\/([0-9.]+)/);if(_.Hb&&!_.$a())return Qj(/Version\/([0-9.]+)/);if(_.Db||_.Eb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Qa);if(a)return a[1]+"."+a[2]}else if(_.Fb)return(a=Qj(/Android\s+([0-9.]+)/))?a:Qj(/Version\/([0-9.]+)/);return""}();

}catch(e){_._DumpException(e)}
try{
var Zj,bk,ek,fk,gk;_.Sj=function(a,c){if(c<a.w){c+=a.A;var d=a.j[c];return d===_.Kb?a.j[c]=[]:d}d=a.o[c];return d===_.Kb?a.o[c]=[]:d};_.Tj=function(a,c,d){a.b||(a.b={});if(!a.b[d]){for(var e=_.Sj(a,d),f=[],g=0;g<e.length;g++)f[g]=new c(e[g]);a.b[d]=f}c=a.b[d];c==_.Kb&&(c=a.b[d]=[]);return c};_.Uj=function(a){return Array.prototype.concat.apply([],arguments)};_.Vj=function(a){return(0,window.encodeURIComponent)(String(a))};
_.Wj=function(a,c,d,e,f,g,h){var m="";a&&(m+=a+":");d&&(m+="//",c&&(m+=c+"@"),m+=d,e&&(m+=":"+e));f&&(m+=f);g&&(m+="?"+g);h&&(m+="#"+h);return m};_.Xj=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.Yj=function(a){a=a.match(_.Xj)[1]||null;!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1));return a?a.toLowerCase():""};
Zj=function(a,c){if(!c)return a;var d=a.indexOf("#");0>d&&(d=a.length);var e=a.indexOf("?");if(0>e||e>d){e=d;var f=""}else f=a.substring(e+1,d);a=[a.substr(0,e),f,a.substr(d)];d=a[1];a[1]=c?d?d+"&"+c:c:d;return a[0]+(a[1]?"?"+a[1]:"")+a[2]};_.ak=function(a,c,d){if(_.p(c))for(var e=0;e<c.length;e++)_.ak(a,String(c[e]),d);else null!=c&&d.push(a+(""===c?"":"="+_.Vj(c)))};bk=function(a,c){var d=[];for(c=c||0;c<a.length;c+=2)_.ak(a[c],a[c+1],d);return d.join("&")};
_.ck=function(a,c){var d=2==arguments.length?bk(arguments[1],0):bk(arguments,1);return Zj(a,d)};_.dk=function(a,c,d){d=null!=d?"="+_.Vj(d):"";return Zj(a,c+d)};ek=function(a,c,d,e){for(var f=d.length;0<=(c=a.indexOf(d,c))&&c<e;){var g=a.charCodeAt(c-1);if(38==g||63==g)if(g=a.charCodeAt(c+f),!g||61==g||38==g||35==g)return c;c+=f+1}return-1};fk=/#|$/;gk=/[?&]($|#)/; _.hk=function(a,c){for(var d=a.search(fk),e=0,f,g=[];0<=(f=ek(a,e,c,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));return g.join("").replace(gk,"$1")};_.ik=function(a,c,d){return _.dk(_.hk(a,c),c,d)};

}catch(e){_._DumpException(e)}
try{
var jk,kk,lk,nk,ok,qk,sk,tk,uk;jk=function(a){if(_.p(a)){for(var c=Array(a.length),d=0;d<a.length;d++){var e=a[d];null!=e&&(c[d]="object"==typeof e?jk(e):e)}return c}if(_.Jb&&a instanceof window.Uint8Array)return new window.Uint8Array(a);c={};for(d in a)e=a[d],null!=e&&(c[d]="object"==typeof e?jk(e):e);return c};kk=function(a){return new a.constructor(jk(a.Vb()))};lk=function(a,c){a.f=c;a.Db&&a.Xb?(a.stop(),a.start()):a.Db&&a.stop()};
_.mk=function(a,c,d){a.b||(a.b={});d=d||[];for(var e=[],f=0;f<d.length;f++)e[f]=d[f].Vb();a.b[c]=d;_.D(a,c,e)};nk=function(a){return a.f||(a.f=a.o())};ok=function(a){if(a.Ta&&"function"==typeof a.Ta)return a.Ta();if(_.n(a))return a.split("");if(_.bd(a)){for(var c=[],d=a.length,e=0;e<d;e++)c.push(a[e]);return c}return _.Be(a)};qk=function(a){a:{var c=pk;for(var d=a.length,e=_.n(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&c.call(void 0,e[f],f,a)){c=f;break a}c=-1}return 0>c?null:_.n(a)?a.charAt(c):a[c]};
sk=function(){this.b=rk};sk.prototype.f=function(){return!!this.b};tk=function(a,c){return a+Math.random()*(c-a)};uk=function(a){var c=c||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,c))}};
_.vk=function(a,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(c,void 0);else if(_.bd(a)||_.n(a))(0,_.Ha)(a,c,void 0);else{if(a.lb&&"function"==typeof a.lb)var d=a.lb();else if(a.Ta&&"function"==typeof a.Ta)d=void 0;else if(_.bd(a)||_.n(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=ok(a);f=e.length;for(var g=0;g<f;g++)c.call(void 0,e[g],d&&d[g],a)}};
var wk=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),d=c.indexOf("/");-1!=d&&(c=c.substring(0,d));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a&&"chrome-search"!==a&&"app"!==a)throw Error("S`"+a);d="";var e=c.indexOf(":");if(-1!=e){var f=c.substring(e+1);c=c.substring(0, e);if("http"===a&&"80"!==f||"https"===a&&"443"!==f)d=":"+f}return a+"://"+c+d};
var xk=function(){function a(){f[0]=1732584193;f[1]=4023233417;f[2]=2562383102;f[3]=271733878;f[4]=3285377520;w=t=0}function c(a){for(var c=h,d=0;64>d;d+=4)c[d/4]=a[d]<<24|a[d+1]<<16|a[d+2]<<8|a[d+3];for(d=16;80>d;d++)a=c[d-3]^c[d-8]^c[d-14]^c[d-16],c[d]=(a<<1|a>>>31)&4294967295;a=f[0];var e=f[1],g=f[2],m=f[3],q=f[4];for(d=0;80>d;d++){if(40>d)if(20>d){var t=m^e&(g^m);var F=1518500249}else t=e^g^m,F=1859775393;else 60>d?(t=e&g|m&(e|g),F=2400959708):(t=e^g^m,F=3395469782);t=((a<<5|a>>>27)&4294967295)+
t+q+F+c[d]&4294967295;q=m;m=g;g=(e<<30|e>>>2)&4294967295;e=a;a=t}f[0]=f[0]+a&4294967295;f[1]=f[1]+e&4294967295;f[2]=f[2]+g&4294967295;f[3]=f[3]+m&4294967295;f[4]=f[4]+q&4294967295}function d(a,d){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var e=[],f=0,h=a.length;f<h;++f)e.push(a.charCodeAt(f));a=e}d||(d=a.length);e=0;if(0==t)for(;e+64<d;)c(a.slice(e,e+64)),e+=64,w+=64;for(;e<d;)if(g[t++]=a[e++],w++,64==t)for(t=0,c(g);e+64<d;)c(a.slice(e,e+64)),e+=64,w+=64}
function e(){var a=[],e=8*w;56>t?d(m,56-t):d(m,64-(t-56));for(var h=63;56<=h;h--)g[h]=e&255,e>>>=8;c(g);for(h=e=0;5>h;h++)for(var q=24;0<=q;q-=8)a[e++]=f[h]>>q&255;return a}for(var f=[],g=[],h=[],m=[128],q=1;64>q;++q)m[q]=0;var t,w;a();return{reset:a,update:d,digest:e,Hg:function(){for(var a=e(),c="",d=0;d<a.length;d++)c+="0123456789ABCDEF".charAt(Math.floor(a[d]/16))+"0123456789ABCDEF".charAt(a[d]%16);return c}}};
var zk=function(a,c,d){var e=[],f=[];if(1==(_.p(d)?2:1))return f=[c,a],(0,_.Ha)(e,function(a){f.push(a)}),yk(f.join(" "));var g=[],h=[];(0,_.Ha)(d,function(a){h.push(a.key);g.push(a.value)});d=Math.floor((new Date).getTime()/1E3);f=0==g.length?[d,c,a]:[g.join(":"),d,c,a];(0,_.Ha)(e,function(a){f.push(a)});a=yk(f.join(" "));a=[d,a];0==h.length||a.push(h.join(""));return a.join("_")},yk=function(a){var c=xk();c.update(a);return c.Hg().toLowerCase()};
var Ak=function(a){var c=wk(String(_.l.location.href)),d=_.l.__OVERRIDE_SID;null==d&&(d=(new _.xj(window.document)).get("SID"));if(d&&(c=(d=0==c.indexOf("https:")||0==c.indexOf("chrome-extension:"))?_.l.__SAPISID:_.l.__APISID,null==c&&(c=(new _.xj(window.document)).get(d?"SAPISID":"APISID")),c)){d=d?"SAPISIDHASH":"APISIDHASH";var e=String(_.l.location.href);return e&&c&&d?[d,zk(wk(e),c,a||null)].join(" "):null}return null};
var Bk;Bk=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};_.Ck=function(a){a=String(a);if(Bk(a))try{return eval("("+a+")")}catch(c){}throw Error("T`"+a);};_.Dk=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
var Fk=function(){return!Ek()&&(_.x("iPod")||_.x("iPhone")||_.x("Android")||_.x("IEMobile"))},Ek=function(){return _.x("iPad")||_.x("Android")&&!_.x("Mobile")||_.x("Silk")};var Gk=function(a){this.b=this.f=this.j=a};Gk.prototype.reset=function(){this.b=this.f=this.j};Gk.prototype.wa=function(){return this.f};var Hk=function(a){_.O.call(this);this.headers=new _.Mj;this.C=a||null;this.f=!1;this.B=this.b=null;this.G="";this.j=this.H=this.A=this.D=!1;this.w=0;this.o=null;this.N="";this.L=this.M=!1},Ik,Jk,Kk;_.v(Hk,_.O);Ik=/^https?$/i;Jk=["POST","PUT"];Kk=[];_.Lk=function(a,c,d,e,f,g,h){var m=new Hk;Kk.push(m);c&&m.K("complete",c);m.tb("ready",m.R);g&&(m.w=Math.max(0,g));h&&(m.M=h);m.send(a,d,e,f)};Hk.prototype.R=function(){this.ha();_.Vd(Kk,this)};
Hk.prototype.send=function(a,c,d,e){if(this.b)throw Error("V`"+this.G+"`"+a);c=c?c.toUpperCase():"GET";this.G=a;this.D=!1;this.f=!0;this.b=this.C?this.C.b():_.Fj.b();this.B=this.C?nk(this.C):nk(_.Fj);this.b.onreadystatechange=(0,_.r)(this.P,this);try{this.H=!0,this.b.open(c,String(a),!0),this.H=!1}catch(g){Mk(this);return}a=d||"";var f=new _.Mj(this.headers);e&&_.vk(e,function(a,c){f.set(c,a)});e=qk(f.lb());d=_.l.FormData&&a instanceof _.l.FormData;!_.Ma(Jk,c)||e||d||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,c){this.b.setRequestHeader(c,a)},this);this.N&&(this.b.responseType=this.N);"withCredentials"in this.b&&this.b.withCredentials!==this.M&&(this.b.withCredentials=this.M);try{Nk(this),0<this.w&&((this.L=Ok(this.b))?(this.b.timeout=this.w,this.b.ontimeout=(0,_.r)(this.U,this)):this.o=_.rf(this.U,this.w,this)),this.A=!0,this.b.send(a),this.A=!1}catch(g){Mk(this)}};var Ok=function(a){return _.y&&_.wb(9)&&_.va(a.timeout)&&_.ua(a.ontimeout)},pk=function(a){return"content-type"==a.toLowerCase()};
Hk.prototype.U=function(){"undefined"!=typeof _.ta&&this.b&&(this.dispatchEvent("timeout"),this.abort(8))};var Mk=function(a){a.f=!1;a.b&&(a.j=!0,a.b.abort(),a.j=!1);Pk(a);Qk(a)},Pk=function(a){a.D||(a.D=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};Hk.prototype.abort=function(){this.b&&this.f&&(this.f=!1,this.j=!0,this.b.abort(),this.j=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Qk(this))};
Hk.prototype.O=function(){this.b&&(this.f&&(this.f=!1,this.j=!0,this.b.abort(),this.j=!1),Qk(this,!0));Hk.J.O.call(this)};Hk.prototype.P=function(){this.Ga||(this.H||this.A||this.j?Rk(this):this.S())};Hk.prototype.S=function(){Rk(this)};
var Rk=function(a){if(a.f&&"undefined"!=typeof _.ta&&(!a.B[1]||4!=(a.b?a.b.readyState:0)||2!=a.mb()))if(a.A&&4==(a.b?a.b.readyState:0))_.rf(a.P,0,a);else if(a.dispatchEvent("readystatechange"),4==(a.b?a.b.readyState:0)){a.f=!1;try{a.$c()?(a.dispatchEvent("complete"),a.dispatchEvent("success")):(a.mb(),Pk(a))}finally{Qk(a)}}},Qk=function(a,c){if(a.b){Nk(a);var d=a.b,e=a.B[0]?_.wa:null;a.b=null;a.B=null;c||a.dispatchEvent("ready");try{d.onreadystatechange=e}catch(f){}}},Nk=function(a){a.b&&a.L&&(a.b.ontimeout=
null);a.o&&(_.l.clearTimeout(a.o),a.o=null)};Hk.prototype.$c=function(){var a=this.mb(),c;if(!(c=_.Dj(a))){if(a=0===a)a=_.Yj(String(this.G)),a=!Ik.test(a);c=a}return c};Hk.prototype.mb=function(){try{return 2<(this.b?this.b.readyState:0)?this.b.status:-1}catch(a){return-1}};Hk.prototype.kf=function(){try{return this.b?this.b.responseText:""}catch(a){return""}};Hk.prototype.le=function(){if(this.b){a:{var a=this.b.responseText;if(_.l.JSON)try{var c=_.l.JSON.parse(a);break a}catch(d){}c=_.Ck(a)}return c}};
var Sk=!1,Tk="",Uk=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")},Vk;
(function(){if(window.navigator.plugins&&window.navigator.plugins.length){var a=window.navigator.plugins["Shockwave Flash"];if(a&&(Sk=!0,a.description)){Tk=Uk(a.description);return}if(window.navigator.plugins["Shockwave Flash 2.0"]){Sk=!0;Tk="2.0.0.11";return}}if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length&&(a=window.navigator.mimeTypes["application/x-shockwave-flash"],Sk=!(!a||!a.enabledPlugin))){Tk=Uk(a.enabledPlugin.description);return}try{var c=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");
Sk=!0;Tk=Uk(c.GetVariable("$version"));return}catch(d){}try{c=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");Sk=!0;Tk="6.0.21";return}catch(d){}try{c=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Sk=!0,Tk=Uk(c.GetVariable("$version"))}catch(d){}})();Vk=Sk;_.Wk=Tk;
var Xk=function(a,c,d){_.Lk(a.url,function(a){a=a.target;a.$c()?c(a.kf()):d(a.mb())},a.f,a.body,a.b,0,a.withCredentials)};var Yk,al;_.Zk=function(a){_.A(this,a,0,27,Yk)};_.v(_.Zk,_.z);Yk=[3,20];_.$k=function(a){var c=(0,_.Ea)().toString();_.D(a,1,c)};al=function(a){_.A(this,a,0,-1,null)};_.v(al,_.z);var bl=function(a){_.A(this,a,0,-1,null)};_.v(bl,_.z);var cl=function(a){_.A(this,a,0,-1,null)};_.v(cl,_.z);var el=function(a){_.A(this,a,0,15,dl)};_.v(el,_.z);var dl=[3,5],fl=function(a){var c=(0,_.Ea)().toString();_.D(a,4,c)},hl=function(a){_.A(this,a,0,6,gl)};_.v(hl,_.z);var gl=[5],rk=function(a){_.A(this,a,0,-1,null)}; _.v(rk,_.z);var il=new sk;
var jl=function(a,c,d,e,f,g,h,m,q){_.O.call(this);this.W=a;this.N=c||_.wa;this.o=new el;this.V=e;this.b=[];this.R="";this.$=_.Yc(tk,0,1);this.C=f||null;this.w=d||null;this.D=h||!1;this.M=q||null;this.T=!1;this.S=this.H=-1;this.L=!1;this.X=!m;this.G=0;this.Y=1;this.U=g||!1;a=new cl;_.D(a,1,1);this.P=a;_.Aj(this.o,1,a);_.D(this.o,2,this.W);this.j=new Gk(1E4);this.f=new _.qf(this.j.wa());_.nf(this,this.f);_.N(this.f,"tick",uk(this.flush),!1,this);this.B=new _.qf(6E5);_.nf(this,this.B);_.N(this.B,"tick",
uk(this.flush),!1,this);this.D||this.B.start();this.U||(_.N(_.Kj(),"beforeunload",this.A,!1,this),_.N(_.Kj(),"unload",this.A,!1,this),_.N(window.document,"pagehide",this.A,!1,this))};_.v(jl,_.O);jl.prototype.O=function(){this.A();jl.J.O.call(this)};var kl=function(a){a.C||(a.C=.01>a.$()?"https://www.google.com/log?format=json":"https://play.google.com/log?format=json");return a.C};jl.prototype.td=function(a){if(a instanceof _.Zk)this.log(a);else{var c=new _.Zk;a=a.f();_.D(c,8,a);this.log(c)}};
_.ll=function(a,c){a.j=new Gk(1>c?1:c);lk(a.f,a.j.wa())};jl.prototype.log=function(a){a=kk(a);var c=this.Y++;_.D(a,21,c);for(_.B(a,1)||_.$k(a);1E3<=this.b.length;)this.b.shift(),++this.G;this.b.push(a);this.dispatchEvent(new ml(a));this.D||this.f.Xb||this.f.start()};
jl.prototype.flush=function(a,c){if(0==this.b.length)a&&a();else{var d=(0,_.Ea)();if(this.S>d&&this.H<d)c&&c("throttled");else{var e=kk(this.o);fl(e);_.mk(e,3,this.b);_.D(e,14,this.G);d={};var f=this.N();f&&(d.Authorization=f);var g=kl(this);this.w&&(d["X-Goog-AuthUser"]=this.w,g=_.dk(g,"authuser",this.w));this.M&&(d["X-Goog-PageId"]=this.M,g=_.dk(g,"pageId",this.M));if(f&&this.R==f)c&&c("stale-auth-token");else{this.b=[];this.f.Xb&&this.f.stop();this.G=0;var h=e.f();d={url:g,body:h,j:1,b:d,f:"POST",
withCredentials:this.X};g=(0,_.r)(function(c){this.j.reset();lk(this.f,this.j.wa());if(c){try{var d=JSON.parse(c.replace(")]}'\n",""));var e=new hl(d)}catch(w){}e&&(c=_.C(e,1,"-1"),c=Number(c),0<c&&(this.H=(0,_.Ea)(),this.S=this.H+c),e.o?(e.b||(e.b={}),il.f()?(!e.b[175237375]&&e.o[175237375]&&(e.b[175237375]=new il.b(e.o[175237375])),e=e.b[175237375]):e=e.o[175237375]):e=void 0,e&&(e=_.C(e,1,-1),-1!=e&&(this.L||_.ll(this,e))))}a&&a()},this);h=(0,_.r)(function(a){var d=_.Tj(e,_.Zk,3),g=this.j;g.b=
Math.min(3E5,2*g.b);g.f=Math.min(3E5,g.b+Math.round(.2*(Math.random()-.5)*g.b));lk(this.f,this.j.wa());401==a&&f&&(this.R=f);if(500<=a&&600>a||401==a||0==a)this.b=d.concat(this.b),this.D||this.f.Xb||this.f.start();c&&c("net-send-failed",a)},this);this.V(d,g,h)}}}};jl.prototype.A=function(){this.T&&nl(this);this.flush()};
var nl=function(a){ol(a,function(a,d){a=_.dk(a,"format","json");return _.Kj().navigator.sendBeacon(a,d.f())})},ol=function(a,c){if(0!=a.b.length){var d=_.hk(kl(a),"format");d=_.ck(d,"auth",a.N(),"authuser",a.w||"0");for(var e=0;10>e&&a.b.length;++e){var f=a.b.slice(0,32),g=kk(a.o);fl(g);_.mk(g,3,f);if(!c(d,g))break;a.b=a.b.slice(f.length)}}},ml=function(){this.type="event-logged"};_.v(ml,_.Yd);
var pl=_.db?"opera":_.eb?"edge":_.y?"ie":_.Cb?"firefox":_.Db?"iphone":_.Eb?"ipad":_.Fb?"android":_.Gb?"chrome":_.Hb?"safari":"unknown";_.ql=function(a,c,d,e,f,g){jl.call(this,a,Ak,c,Xk,d,e,f,void 0,g);a=this.P;e=this.U;c=new bl;d=new al;f=Fk()||Ek()?Ek()?2:Fk()?1:0:3;_.D(c,6,_.x("Android")?3:_.x("CrOS")?5:_.x("CrKey")?9:_.x("Windows")?2:_.x("iPad")?6:_.Za()?7:_.x("iPod")?8:_.x("Linux")?4:_.x("Macintosh")?1:0);g=_.Qa;var h="";_.x("Windows")?(h=/Windows (?:NT|Phone) ([0-9.]+)/,h=(g=h.exec(g))?g[1]:"0.0"):_.$a()?(h=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,h=(g=h.exec(g))&&g[1].replace(/_/g,".")):_.x("Macintosh")?(h=/Mac OS X ([0-9_.]+)/,
h=(g=h.exec(g))?g[1].replace(/_/g,"."):"10"):_.x("Android")?(h=/Android\s+([^\);]+)(\)|;)/,h=(g=h.exec(g))&&g[1]):_.x("CrOS")&&(h=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,h=(g=h.exec(g))&&g[1]);_.D(c,2,h||"");_.D(c,3,f);e||(e=_.Kj(),f=window.document.documentElement.getAttribute("lang"),_.D(c,5,f),_.D(d,1,e.navigator.language||e.navigator.browserLanguage));_.D(d,2,pl);_.D(d,3,_.Rj);Vk&&_.D(d,4,_.Wk);_.Aj(a,11,c);_.Aj(a,9,d);_.Aj(this.o,1,this.P)};_.v(_.ql,jl);

}catch(e){_._DumpException(e)}
try{
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
var rl=window,sl=window.document,tl=rl.location,ul=function(){},vl=/\[native code\]/,wl=function(a,c,d){return a[c]=a[c]||d},xl=function(a){a=a.sort();for(var c=[],d=void 0,e=0;e<a.length;e++){var f=a[e];f!=d&&c.push(f);d=f}return c},yl=function(){var a;if((a=Object.create)&&vl.test(a))a=a(null);else{a={};for(var c in a)a[c]=void 0}return a},zl=wl(rl,"gapi",{});
var Al;Al=wl(rl,"___jsl",yl());wl(Al,"I",0);wl(Al,"hel",10);var Bl=function(){var a=tl.href;if(Al.dpo)var c=Al.h;else{c=Al.h;var d=/([#].*&|[#])jsh=([^&#]*)/g,e=/([?#].*&|[?#])jsh=([^&#]*)/g;if(a=a&&(d.exec(a)||e.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(f){}}return c},Cl=function(a){var c=wl(Al,"PQ",[]);Al.PQ=[];var d=c.length;if(0===d)a();else for(var e=0,f=function(){++e===d&&a()},g=0;g<d;g++)c[g](f)},Dl=function(a){return wl(wl(Al,"H",yl()),a,yl())};
var El=wl(Al,"perf",yl());wl(El,"g",yl());var Fl=wl(El,"i",yl());wl(El,"r",[]);yl();yl();var Hl=function(a,c,d){c&&0<c.length&&(c=Gl(c),d&&0<d.length&&(c+="___"+Gl(d)),28<c.length&&(c=c.substr(0,28)+(c.length-28)),d=c,c=wl(Fl,"_p",yl()),wl(c,d,yl())[a]=(new Date).getTime(),c=El.r,"function"===typeof c?c(a,"_p",d):c.push([a,"_p",d]))},Gl=function(a){return a.join("__").replace(/\./g,"_").replace(/\-/g,"_").replace(/,/g,"_")};
var Il=yl(),Jl=[],Kl=function(a){throw Error("W`"+(a?": "+a:""));};Jl.push(["jsl",function(a){for(var c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];"object"==typeof d?Al[c]=wl(Al,c,[]).concat(d):wl(Al,c,d)}if(c=a.u)a=wl(Al,"us",[]),a.push(c),(c=/^https:(.*)$/.exec(c))&&a.push("http:"+c[1])}]);
var Ll=/^(\/[a-zA-Z0-9_\-]+)+$/,Ml=[/\/amp\//,/\/amp$/,/^\/amp$/],Nl=/^[a-zA-Z0-9\-_\.,!]+$/,Ol=/^gapi\.loaded_[0-9]+$/,Pl=/^[a-zA-Z0-9,._-]+$/,Tl=function(a,c,d,e){var f=a.split(";"),g=f.shift(),h=Il[g],m=null;h?m=h(f,c,d,e):Kl("no hint processor for: "+g);m||Kl("failed to generate load url");c=m;d=c.match(Ql);(e=c.match(Rl))&&1===e.length&&Sl.test(c)&&d&&1===d.length||Kl("failed sanity: "+a);return m},Wl=function(a,c,d,e){a=Ul(a);Ol.test(d)||Kl("invalid_callback");c=Vl(c);e=e&&e.length?Vl(e):null;
var f=function(a){return(0,window.encodeURIComponent)(a).replace(/%2C/g,",")};return[(0,window.encodeURIComponent)(a.pathPrefix).replace(/%2C/g,",").replace(/%2F/g,"/"),"/k=",f(a.version),"/m=",f(c),e?"/exm="+f(e):"","/rt=j/sv=1/d=1/ed=1",a.Re?"/am="+f(a.Re):"",a.Sf?"/rs="+f(a.Sf):"",a.Vf?"/t="+f(a.Vf):"","/cb=",f(d)].join("")},Ul=function(a){"/"!==a.charAt(0)&&Kl("relative path");for(var c=a.substring(1).split("/"),d=[];c.length;){a=c.shift();if(!a.length||0==a.indexOf("."))Kl("empty/relative directory");
else if(0<a.indexOf("=")){c.unshift(a);break}d.push(a)}a={};for(var e=0,f=c.length;e<f;++e){var g=c[e].split("="),h=(0,window.decodeURIComponent)(g[0]),m=(0,window.decodeURIComponent)(g[1]);2==g.length&&h&&m&&(a[h]=a[h]||m)}c="/"+d.join("/");Ll.test(c)||Kl("invalid_prefix");d=0;for(e=Ml.length;d<e;++d)Ml[d].test(c)&&Kl("invalid_prefix");d=Xl(a,"k",!0);e=Xl(a,"am");f=Xl(a,"rs");a=Xl(a,"t");return{pathPrefix:c,version:d,Re:e,Sf:f,Vf:a}},Vl=function(a){for(var c=[],d=0,e=a.length;d<e;++d){var f=a[d].replace(/\./g,
"_").replace(/-/g,"_");Pl.test(f)&&c.push(f)}return c.join(",")},Xl=function(a,c,d){a=a[c];!a&&d&&Kl("missing: "+c);if(a){if(Nl.test(a))return a;Kl("invalid: "+c)}return null},Sl=/^https?:\/\/[a-z0-9_.-]+\.google(rs)?\.com(:\d+)?\/[a-zA-Z0-9_.,!=\-\/]+$/,Rl=/\/cb=/g,Ql=/\/\//g,Yl=function(){var a=Bl();if(!a)throw Error("X");return a};Il.m=function(a,c,d,e){(a=a[0])||Kl("missing_hint");return"https://apis.google.com"+Wl(a,c,d,e)};
var Zl=(0,window.decodeURI)("%73cript"),$l=/^[-+_0-9\/A-Za-z]+={0,2}$/,am=function(a,c){for(var d=[],e=0;e<a.length;++e){var f=a[e],g;if(g=f){a:{for(g=0;g<c.length;g++)if(c[g]===f)break a;g=-1}g=0>g}g&&d.push(f)}return d},bm=function(){var a=Al.nonce;return void 0!==a?a&&a===String(a)&&a.match($l)?a:Al.nonce=null:sl.querySelector?(a=sl.querySelector("script[nonce]"))?(a=a.nonce||a.getAttribute("nonce")||"",a&&a===String(a)&&a.match($l)?Al.nonce=a:Al.nonce=null):null:null},dm=function(a){if("loading"!=
sl.readyState)cm(a);else{var c=bm(),d="";null!==c&&(d=' nonce="'+c+'"');sl.write("<"+Zl+' src="'+(0,window.encodeURI)(a)+'"'+d+"></"+Zl+">")}},cm=function(a){var c=sl.createElement(Zl);c.setAttribute("src",a);a=bm();null!==a&&c.setAttribute("nonce",a);c.async="true";(a=sl.getElementsByTagName(Zl)[0])?a.parentNode.insertBefore(c,a):(sl.head||sl.body||sl.documentElement).appendChild(c)},em=function(a,c){var d=c&&c._c;if(d)for(var e=0;e<Jl.length;e++){var f=Jl[e][0],g=Jl[e][1];g&&Object.prototype.hasOwnProperty.call(d,
f)&&g(d[f],a,c)}},gm=function(a,c,d){fm(function(){var d=c===Bl()?wl(zl,"_",yl()):yl();d=wl(Dl(c),"_",d);a(d)},d)},im=function(a,c){var d=c||{};"function"==typeof c&&(d={},d.callback=c);em(a,d);c=a?a.split(":"):[];var e=d.h||Yl(),f=wl(Al,"ah",yl());if(f["::"]&&c.length){a=[];for(var g=null;g=c.shift();){var h=g.split(".");h=f[g]||f[h[1]&&"ns:"+h[0]||""]||e;var m=a.length&&a[a.length-1]||null,q=m;m&&m.hint==h||(q={hint:h,ud:[]},a.push(q));q.ud.push(g)}var t=a.length;if(1<t){var w=d.callback;w&&(d.callback=
function(){0==--t&&w()})}for(;c=a.shift();)hm(c.ud,d,c.hint)}else hm(c||[],d,e)},hm=function(a,c,d){a=xl(a)||[];var e=c.callback,f=c.config,g=c.timeout,h=c.ontimeout,m=c.onerror,q=void 0;"function"==typeof m&&(q=m);var t=null,w=!1;if(g&&!h||!g&&h)throw"Timeout requires both the timeout parameter and ontimeout parameter to be set";m=wl(Dl(d),"r",[]).sort();var F=wl(Dl(d),"L",[]).sort(),qa=[].concat(m),Sa=function(a,c){if(w)return 0;rl.clearTimeout(t);F.push.apply(F,ja);var e=((zl||{}).config||{}).update;
e?e(f):f&&wl(Al,"cu",[]).push(f);if(c){Hl("me0",a,qa);try{gm(c,d,q)}finally{Hl("me1",a,qa)}}return 1};0<g&&(t=rl.setTimeout(function(){w=!0;h()},g));var ja=am(a,F);if(ja.length){ja=am(a,m);var Ia=wl(Al,"CP",[]),Bb=Ia.length;Ia[Bb]=function(a){if(!a)return 0;Hl("ml1",ja,qa);var c=function(c){Ia[Bb]=null;Sa(ja,a)&&Cl(function(){e&&e();c()})},d=function(){var a=Ia[Bb+1];a&&a()};0<Bb&&Ia[Bb-1]?Ia[Bb]=function(){c(d)}:c(d)};if(ja.length){var re="loaded_"+Al.I++;zl[re]=function(a){Ia[Bb](a);zl[re]=null};
a=Tl(d,ja,"gapi."+re,m);m.push.apply(m,ja);Hl("ml0",ja,qa);c.sync||rl.___gapisync?dm(a):cm(a)}else Ia[Bb](ul)}else Sa(ja)&&e&&e()},fm=function(a,c){if(Al.hee&&0<Al.hel)try{return a()}catch(d){c&&c(d),Al.hel--,im("debug_error",function(){try{window.___jsl.hefn(d)}catch(e){throw d;}})}else try{return a()}catch(d){throw c&&c(d),d;}};zl.load=function(a,c){return fm(function(){return im(a,c)})};

}catch(e){_._DumpException(e)}
try{
var jm,pm,rm,zm,sm,um,tm,xm,vm,qm,Am,Bm,wm;jm=function(a,c){if(a){a=a.split("&");for(var d=0;d<a.length;d++){var e=a[d].indexOf("="),f=null;if(0<=e){var g=a[d].substring(0,e);f=a[d].substring(e+1)}else g=a[d];c(g,f?(0,window.decodeURIComponent)(f.replace(/\+/g," ")):"")}}};
_.km=function(a,c){this.f=this.B=this.o="";this.C=null;this.A=this.j="";this.w=!1;var d;a instanceof _.km?(this.w=_.ua(c)?c:a.w,_.lm(this,a.o),this.B=a.B,this.f=a.f,_.mm(this,a.C),this.j=a.j,_.nm(this,_.om(a.b)),this.A=a.A):a&&(d=String(a).match(_.Xj))?(this.w=!!c,_.lm(this,d[1]||"",!0),this.B=pm(d[2]||""),this.f=pm(d[3]||"",!0),_.mm(this,d[4]),this.j=pm(d[5]||"",!0),_.nm(this,d[6]||"",!0),this.A=pm(d[7]||"")):(this.w=!!c,this.b=new qm(null,this.w))};
_.km.prototype.toString=function(){var a=[],c=this.o;c&&a.push(rm(c,sm,!0),":");var d=this.f;if(d||"file"==c)a.push("//"),(c=this.B)&&a.push(rm(c,sm,!0),"@"),a.push(_.Vj(d).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),d=this.C,null!=d&&a.push(":",String(d));if(d=this.j)this.f&&"/"!=d.charAt(0)&&a.push("/"),a.push(rm(d,"/"==d.charAt(0)?tm:um,!0));(d=this.b.toString())&&a.push("?",d);(d=this.A)&&a.push("#",rm(d,vm));return a.join("")};_.lm=function(a,c,d){a.o=d?pm(c,!0):c;a.o&&(a.o=a.o.replace(/:$/,""))};
_.mm=function(a,c){if(c){c=Number(c);if((0,window.isNaN)(c)||0>c)throw Error("Y`"+c);a.C=c}else a.C=null};_.nm=function(a,c,d){c instanceof qm?(a.b=c,wm(a.b,a.w)):(d||(c=rm(c,xm)),a.b=new qm(c,a.w))};_.ym=function(a,c,d){a.b.set(c,d);return a};pm=function(a,c){return a?c?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};rm=function(a,c,d){return _.n(a)?(a=(0,window.encodeURI)(a).replace(c,zm),d&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
zm=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};sm=/[#\/\?@]/g;um=/[#\?:]/g;tm=/[#\?]/g;xm=/[#\?@]/g;vm=/#/g;qm=function(a,c){this.f=this.b=null;this.j=a||null;this.o=!!c};Am=function(a){a.b||(a.b=new _.Mj,a.f=0,a.j&&jm(a.j,function(c,d){a.add((0,window.decodeURIComponent)(c.replace(/\+/g," ")),d)}))};qm.prototype.add=function(a,c){Am(this);this.j=null;a=Bm(this,a);var d=this.b.get(a);d||this.b.set(a,d=[]);d.push(c);this.f+=1;return this};
qm.prototype.remove=function(a){Am(this);a=Bm(this,a);return _.Pj(this.b,a)?(this.j=null,this.f-=this.b.get(a).length,this.b.remove(a)):!1};qm.prototype.clear=function(){this.b=this.j=null;this.f=0};qm.prototype.vc=function(){Am(this);return 0==this.f};var Cm=function(a,c){Am(a);c=Bm(a,c);return _.Pj(a.b,c)};_.k=qm.prototype;_.k.forEach=function(a,c){Am(this);this.b.forEach(function(d,e){(0,_.Ha)(d,function(d){a.call(c,d,e,this)},this)},this)};
_.k.lb=function(){Am(this);for(var a=this.b.Ta(),c=this.b.lb(),d=[],e=0;e<c.length;e++)for(var f=a[e],g=0;g<f.length;g++)d.push(c[e]);return d};_.k.Ta=function(a){Am(this);var c=[];if(_.n(a))Cm(this,a)&&(c=_.Uj(c,this.b.get(Bm(this,a))));else{a=this.b.Ta();for(var d=0;d<a.length;d++)c=_.Uj(c,a[d])}return c};_.k.set=function(a,c){Am(this);this.j=null;a=Bm(this,a);Cm(this,a)&&(this.f-=this.b.get(a).length);this.b.set(a,[c]);this.f+=1;return this};
_.k.get=function(a,c){if(!a)return c;a=this.Ta(a);return 0<a.length?String(a[0]):c};_.k.toString=function(){if(this.j)return this.j;if(!this.b)return"";for(var a=[],c=this.b.lb(),d=0;d<c.length;d++){var e=c[d],f=_.Vj(e);e=this.Ta(e);for(var g=0;g<e.length;g++){var h=f;""!==e[g]&&(h+="="+_.Vj(e[g]));a.push(h)}}return this.j=a.join("&")};_.om=function(a){var c=new qm;c.j=a.j;a.b&&(c.b=new _.Mj(a.b),c.f=a.f);return c};Bm=function(a,c){c=String(c);a.o&&(c=c.toLowerCase());return c}; wm=function(a,c){c&&!a.o&&(Am(a),a.j=null,a.b.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<a.length&&(this.j=null,this.b.set(Bm(this,d),_.cd(a)),this.f+=a.length))},a));a.o=c};

}catch(e){_._DumpException(e)}
try{
_.Dm=function(a){_.A(this,a,0,-1,null)};_.v(_.Dm,_.z);/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/

}catch(e){_._DumpException(e)}
try{
var Fm;_.Em=function(a,c,d,e,f,g){d.K(c,e,f,g||a.U||a,a)};Fm=function(){_.G.call(this);this.b=new _.$f};_.v(Fm,_.G);var Gm=new Fm,Hm=["click","keydown","mousedown","touchstart"];Fm.prototype.K=function(a,c,d,e,f){(f||this.b).j(a,Hm,c,d,e)};Fm.prototype.Fa=function(a,c,d,e,f){(f||this.b).Fa(a,Hm,c,d,e)};Fm.prototype.O=function(){this.b.ha();Fm.J.O.call(this)};
_.Jm=function(a,c,d,e,f,g,h){_.lh.call(this,a,d);this.M=g||null;this.B=e;this.$=this.G=null;this.Qc=c;this.R=null;(this.o=h||_.P("gb_b",this.f))&&this.o.setAttribute("aria-expanded","false");this.C=_.Ud("dd");this.C.He(this);(a=_.P("gb_aa",this.f))&&_.Im(this,a,!1);f||this.rb()};_.v(_.Jm,_.lh);_.k=_.Jm.prototype;
_.k.rb=function(){_.Em(this,window.document,Gm,this.uf,!0,this);this.j(window.document,_.gg(27)?"keypress":"keyup",this.Cb,!1,this);this.j(this.f,"mouseover",this.yf,!1,this);this.j(this.f,"mouseout",this.xf,!1,this);this.j(this.f,["keyup","keydown"],this.di,!1,this);this.j(window.document.body,"focusin",this.Qi,!1,this)};_.k.di=function(a){var c=a.target;c instanceof window.Element&&this.lc(c)&&32==a.keyCode&&(a.preventDefault(),a.stopPropagation())};
_.k.Qi=function(){this.Ib()&&(this.lc(window.document.activeElement)||this.vd())};_.k.ue=function(){_.Em(this,this.b,_.Sg,this.Bh,!1,this);_.Vf(this.f,this.b)||(this.j(this.b,"mouseover",this.yf,!1,this),this.j(this.b,"mouseout",this.xf,!1,this));this.K(this.b,"keydown",this.Kh,!0)};_.k.ad=function(){return this.Qc};_.Km=function(a,c){a.R&&a.R.ha();a.R=c};_.k=_.Jm.prototype;_.k.Cd=function(a){var c="click"!=a.type;this.Ib()?this.close(void 0,!0):this.vb(c);a.preventDefault();a.stopPropagation()};
_.k.Bh=function(a){for(a=a.target;a&&a!=this.b;){if("A"==a.tagName&&!_.S(a,"gb_1f")){this.close(!0,!0);break}a=a.parentNode}};_.k.lc=function(a){if(!a)return!1;var c=!!this.b&&_.Vf(this.b,a);return _.Vf(this.f,a)||c};_.k.uf=function(a){this.lc(a.target)||27==a.keyCode||this.close(void 0,!0)};_.k.Kh=function(a){if(9===a.keyCode&&this.Ib()){var c=a.target,d=_.eh(this.b);0<d.length&&(c==d[0]&&a.shiftKey?(d[d.length-1].focus(),a.preventDefault()):c!=d[d.length-1]||a.shiftKey||(d[0].focus(),a.preventDefault()))}};
_.k.yf=function(a){Lm(this,(0,_.r)(this.Vc,this),a)};_.k.xf=function(a){Lm(this,(0,_.r)(this.oe,this),a)};var Lm=function(a,c,d){var e=d.relatedTarget&&(_.Vf(a.f,d.relatedTarget)||_.Vf(a.b,d.relatedTarget)),f=d.relatedTarget&&Mm(a,d.relatedTarget);a=Mm(a,d.target);e||c(0,d);e&&!f||a||c(1,d);!f&&a&&c(2,d)};_.Jm.prototype.Cb=function(a){if(27==a.keyCode){a=_.Xf(window.document);var c=this.lc(a),d=this.Ib();this.close(void 0,!1);d&&c?this.o.focus():a&&a.focus()}};_.Jm.prototype.Vc=_.wa;
_.Jm.prototype.oe=_.wa;var Mm=function(a,c){return c&&a.b?_.S(c,"gb_rb")||_.S(c,"gb_sb")||!!a.b&&_.Vf(a.b,c):!1};_.Jm.prototype.O=function(){_.Jm.J.O.call(this);this.b=null};_.Nm=function(a){if(a.o&&(a=a.o.getAttribute("data-ved")))return{ved:a}};_.k=_.Jm.prototype;_.k.hd=function(a){a?this.vb():this.close()};_.k.Bf=function(){return!1};
_.k.vb=function(a){if(!this.Ib()){this.C.ae(0,this);this.C.Od(this);_.T(this.f,"gb_g");_.T(this.b,"gb_g");this.b.setAttribute("aria-hidden","false");this.o&&this.o.setAttribute("aria-expanded","true");if(_.y&&this.b){var c=_.P("gb_Cf");if(!c){c=_.Q("IFRAME",{"class":"gb_Cf",src:'javascript:""',frameBorder:0});var d=_.P("gb_Cc");d&&d.appendChild(c)}_.U(c,"gb_6a");this.Jd()}this.G&&this.B.log(this.G,_.Nm(this));this.M&&this.Y&&this.M.log(this.Y);this.C.ae(1,this);this.R&&this.R.Ka(!1);a&&this.vd()}};
_.k.vd=function(){var a=_.eh(this.b);a[0]?a[0].focus():this.b.focus()};_.k.Jd=function(){if(_.y&&this.b){var a=_.P("gb_Cf");a&&_.rg(a,_.tg(this.b))}};
_.k.close=function(a,c){return this.Ib()&&this.C.qg(this)?(this.C.Ff(this)&&this.C.Od(null),_.U(this.f,"gb_g"),_.U(this.b,"gb_g"),this.b.setAttribute("aria-hidden","true"),this.o&&(this.o.setAttribute("aria-expanded","false"),!c&&this.lc(window.document.activeElement)&&(0,window.setTimeout)((0,_.r)(this.o.focus,this.o),0)),_.y&&(c=_.P("gb_Cf"))&&_.T(c,"gb_6a"),!a&&this.$&&this.B.log(this.$,_.Nm(this)),!a&&this.M&&this.Ia&&this.M.log(this.Ia),this.C.ae(2,this),!0):!1};
_.k.Ib=function(){return _.S(this.f,"gb_g")};_.Im=function(a,c,d){a.b||(a.b=c,d&&(c=a.b,d=a.f,c&&d&&c.parentNode!=d&&d.appendChild(c)),a.b.setAttribute("aria-hidden","true"),a.o&&_.Em(a,a.o,_.Sg,a.Cd,!1,a),a.ue())};_.Om=function(a){var c=_.Mi(_.Y);a.b&&_.V(a.b,"gb_Ne",c)};

}catch(e){_._DumpException(e)}
try{
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Pm=function(a,c){this.A=[];this.H=a;this.Ga=c||null;this.o=this.b=!1;this.j=void 0;this.G=this.Ya=this.B=!1;this.w=0;this.f=null;this.C=0};Pm.prototype.cancel=function(a){if(this.b)this.j instanceof Pm&&this.j.cancel();else{if(this.f){var c=this.f;delete this.f;a?c.cancel(a):(c.C--,0>=c.C&&c.cancel())}this.H?this.H.call(this.Ga,this):this.G=!0;this.b||(a=new Qm(this),Rm(this),Sm(this,!1,a))}};Pm.prototype.M=function(a,c){this.B=!1;Sm(this,a,c)};
var Sm=function(a,c,d){a.b=!0;a.j=d;a.o=!c;Tm(a)},Rm=function(a){if(a.b){if(!a.G)throw new Um(a);a.G=!1}};Pm.prototype.Rc=function(a){Rm(this);Sm(this,!0,a)};Pm.prototype.D=function(a){Vm(this,a,null,void 0)};var Vm=function(a,c,d,e){a.A.push([c,d,e]);a.b&&Tm(a)};Pm.prototype.then=function(a,c,d){var e,f,g=new _.Xe(function(a,c){e=a;f=c});Vm(this,e,function(a){a instanceof Qm?g.cancel():f(a)});return g.then(a,c,d)};_.Ue(Pm);
var Wm=function(a){return(0,_.La)(a.A,function(a){return _.za(a[1])})},Tm=function(a){if(a.w&&a.b&&Wm(a)){var c=a.w,d=Xm[c];d&&(_.l.clearTimeout(d.b),delete Xm[c]);a.w=0}a.f&&(a.f.C--,delete a.f);c=a.j;for(var e=d=!1;a.A.length&&!a.B;){var f=a.A.shift(),g=f[0],h=f[1];f=f[2];if(g=a.o?h:g)try{var m=g.call(f||a.Ga,c);_.ua(m)&&(a.o=a.o&&(m==c||m instanceof Error),a.j=c=m);if(_.Ve(c)||"function"===typeof _.l.Promise&&c instanceof _.l.Promise)e=!0,a.B=!0}catch(q){c=q,a.o=!0,Wm(a)||(d=!0)}}a.j=c;e&&(m=(0,_.r)(a.M,
a,!0),e=(0,_.r)(a.M,a,!1),c instanceof Pm?(Vm(c,m,e),c.Ya=!0):c.then(m,e));d&&(c=new Ym(c),Xm[c.b]=c,a.w=c.b)},Um=function(){_.Fa.call(this)};_.v(Um,_.Fa);Um.prototype.message="Deferred has already fired";Um.prototype.name="AlreadyCalledError";var Qm=function(){_.Fa.call(this)};_.v(Qm,_.Fa);Qm.prototype.message="Deferred was canceled";Qm.prototype.name="CanceledError";var Ym=function(a){this.b=_.l.setTimeout((0,_.r)(this.j,this),0);this.f=a}; Ym.prototype.j=function(){delete Xm[this.b];throw this.f;};var Xm={};
var Zm=function(a,c){_.G.call(this);this.j=a;this.A=c;this.b=new Pm};_.v(Zm,_.G);Zm.prototype.o=function(a){try{var c=_.Sd("gadgets.config.update");c({"googleapis.config":{gcv:_.I(_.B(a,2)),sessionIndex:_.I(_.B(a,4)),elog:this.j.log,ilog:_.Yc(this.A.log,16)}});c({gwidget:{lang:_.I(_.B(a,5))}});this.b.Rc()}catch(d){this.j.log(d)}};Zm.prototype.f=function(a){a&&this.b.D(a)}; Zm.prototype.init=function(a,c){try{_.B(a,1)?c.f.D((0,_.r)(this.o,this,a)):this.b.Rc(),_.u("gbar.lGC",(0,_.r)(this.f,this)),_.u("gbar.lPWF",(0,_.r)(this.f,this)),_.jc(_.fc.ra(),"api").td()}catch(d){this.j.log(d)}return this};
var $m=function(){_.Fa.call(this)};_.v($m,_.Fa);var an=function(a,c){_.G.call(this);this.j=a;this.b=c;this.f=new Pm};_.v(an,_.G);
an.prototype.init=function(a){try{if(!this.b)throw new $m("gapi-lm");var c={isPlusUser:_.I(_.B(a,4)),"googleapis.config":{signedIn:_.I(_.B(a,5))},lang:_.I(_.B(a,10))},d=_.I(_.B(a,6));d&&(c.iframes={":socialhost:":d});this.b("",{config:c});try{var e=_.Ud("gs");if(!e)throw new $m("gapi-ss");this.b(e.b.join(":"),(0,_.r)(this.f.Rc,this.f));var f=_.cd(e.f);for(a=0;a<f.length;a++)this.b(f[a].ud,f[a].options)}catch(g){this.j.log(g)}}catch(g){this.j.log(g)}return this};
_.bn=function(){var a=_.E(_.vc,_.Tb,14)||new _.Tb,c=new an(_.L,_.Sd("gapi.load"));c.init(a);a=_.E(_.vc,_.Ub,9)||new _.Ub;var d=new Zm(_.L,_.Bc);d.init(a,c);d.f(function(){_.ze(_.K.ra().C,!0)});return d}();
}catch(e){_._DumpException(e)}
try{
var cn=function(a){_.A(this,a,0,-1,null)},pn,qn;_.v(cn,_.z);
var dn=/^(?:(.*?)\.)?([a-zA-Z_$][\w$]*(?:\/.?<)?)?(\(.*\))?@(?::0|((?:http|https|file):\/\/[^\s)]+|javascript:.*))$/,en=/^\s{3,4}at(?: (?:(.*?)\.)?((?:new )?(?:[a-zA-Z_$][\w$]*|<anonymous>))(?: \[as ([a-zA-Z_$][\w$]*)\])?)? (?:\(unknown source\)|\(native\)|\((?:eval at )?((?:http|https|file):\/\/[^\s)]+|javascript:.*)\)|((?:http|https|file):\/\/[^\s)]+|javascript:.*))$/,fn=function(a,c,d,e,f){this.f=a;this.name=c;this.b=d;this.o=e;this.j=f},gn=function(a){this.b=[];if(a.stack){a=a.stack.replace(/\s*$/,
"").split("\n");for(var c=0;c<a.length;c++){var d,e=dn;if(d=a[c].match(en))d=new fn(d[1]||"",d[2]||"",d[3]||"","",d[4]||d[5]||""),this.b.push(d);else if(d=a[c].match(e))d=new fn(d[1]||"",d[2]||"","",d[3]||"",d[4]||""),this.b.push(d)}}},hn=function(a){return(0,_.Ka)(a.b,function(a){var c=[a.f?a.f+".":"",a.name?a.name:"anonymous",a.o,a.b?" [as "+a.b+"]":""];if(a.j){c.push(" at ");a=a.j;var e="",f=a.match(/(.*?)(:\d+(:\d+)?)$/);f&&(a=f[1],e=f[2]);f=window.location.href.replace(/#.*/,"");c.push(a.replace(f,
"[page]").replace(/http.*?extern_js.*?\.js/,"[xjs]"));c.push(e)}return c.join("")})},jn=function(a,c,d,e,f){_.bc.call(this,a,c,d,e,f);this.j=new gn(d)};_.v(jn,_.bc);jn.prototype.b=function(){jn.J.b.call(this);window.console&&window.console.log&&window.console.log("Stack: ",this.j)};
jn.prototype.f=function(a){var c=jn.J.f.call(this,a)+"&jsst=";var d=this.j;a-=c.length;if(4>a)a="";else if(0==d.b.length)a="none";else{d=hn(d);var e;var f=d.length-2;for(e=_.Vj(d.join("\n"));0<f&&e.length>a;f--,e=_.Vj(d.join("\n")))f==d.length-2?d[f]="[...]":d.splice(f,1);a=e.substr(0,a)}return c+a};var kn=function(a,c,d){_.G.call(this);this.f=a;this.j=c;this.o=d};_.v(kn,_.G);kn.prototype.b=function(a,c){return new jn(this.f,this.j,a,this.o,c)};
var ln=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)})},mn=[1],nn=function(a,c,d){_.G.call(this);this.P=d;this.j=_.J(+_.C(a,2,1E-4),.001);this.U=_.J(+_.C(a,10,0),0);this.T=_.J(_.B(a,4),0);this.R=_.J(_.B(a,5),-1);this.N=_.I(_.B(a,7),"");this.H=_.I(_.B(a,6),"");this.M=_.I(_.B(a,8),"");this.D=_.B(a,9);this.S=!!_.B(a,11);this.L=!!_.B(a,12);this.w=!!_.B(a,13);this.A=!!_.B(a,14);this.C=!!_.B(a,15);this.B=
!!_.B(a,16);d=Math.random();this.o=_.H(_.B(a,1))&&d<this.j;this.f=_.H(_.B(a,1))&&d<this.U;this.G="og-"+ln();if(this.o||this.f)a=_.B(a,3)?"https://jmt17.google.com/log":void 0,c=this.b=new _.ql(373,_.I(_.B(c,5)),a),c.L=!0,_.ll(c,1E3),this.b.T=!!_.Kj().navigator.sendBeacon&&(_.Gb||_.Cb&&_.wb(45)),_.nf(this,this.b)};_.v(nn,_.G);
nn.prototype.log=function(a,c){var d=this.o&&!_.Ma(mn,a)||this.f&&!!_.Ma(mn,a);if(d){var e=c||new _.Dm;_.D(e,1,a);_.D(e,2,this.T);_.D(e,4,this.j);_.D(e,3,this.R);_.D(e,11,this.H);_.D(e,10,this.N);_.D(e,5,this.M);window.performance&&window.performance.timing&&_.D(e,14,(new Date).getTime()-window.performance.timing.navigationStart);_.D(e,13,this.D);_.D(e,16,this.S);_.D(e,17,this.L);_.D(e,19,this.G);_.D(e,21,this.w);_.D(e,23,this.A);_.D(e,25,this.C);_.D(e,26,this.B);c=new _.Zk;e=e.f();_.D(c,8,e);this.b.log(c)}this.P&&
window.console.log("Clearcut log called with event = ",a,"("+(d?"":"NOT ")+"sent to server)")};pn=_.E(_.vc,cn,16)||new cn;qn=_.xc()||new _.Qb;_.on=new nn(pn,qn,!1);var rn=_.wc()||new _.Pb;_.E(_.vc,_.Tb,14)||new _.Tb;var sn=+_.C(_.E(_.vc,_.ec,3)||new _.ec,2,.001);_.L.o=new kn(rn,"quantum:gapiBuildLabel",sn);

}catch(e){_._DumpException(e)}
try{
var tn=function(a){_.A(this,a,0,-1,null)};_.v(tn,_.z);var un=function(a){_.A(this,a,0,-1,null)};_.v(un,_.z);un.prototype.B=function(){return _.B(this,7)};un.prototype.C=function(){return _.B(this,8)};var vn=function(a){_.A(this,a,0,-1,null)};_.v(vn,_.z);var wn=function(a){_.A(this,a,0,-1,null)};_.v(wn,_.z);var xn=function(a){_.A(this,a,0,-1,null)};_.v(xn,_.z);
var yn=function(a){_.A(this,a,0,-1,null)};_.v(yn,_.z);var zn=function(){};_.v(zn,_.Ej);zn.prototype.b=function(){var a=new window.XMLHttpRequest;if("withCredentials"in a)return a;if("undefined"!=typeof window.XDomainRequest)return new An;throw Error("$");};zn.prototype.o=function(){return{}};
var An=function(){this.b=new window.XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseText="";this.status=-1;this.statusText="";this.b.onload=(0,_.r)(this.ih,this);this.b.onerror=(0,_.r)(this.nf,this);this.b.onprogress=(0,_.r)(this.Wh,this);this.b.ontimeout=(0,_.r)(this.hi,this)};_.k=An.prototype;_.k.open=function(a,c,d){if(null!=d&&!d)throw Error("aa");this.b.open(a,c)};_.k.send=function(a){if(a)if("string"==typeof a)this.b.send(a);else throw Error("ba");else this.b.send()};
_.k.abort=function(){this.b.abort()};_.k.setRequestHeader=function(){};_.k.getResponseHeader=function(a){return"content-type"==a.toLowerCase()?this.b.contentType:""};_.k.ih=function(){this.status=200;this.responseText=this.b.responseText;Bn(this,4)};_.k.nf=function(){this.status=500;this.responseText="";Bn(this,4)};_.k.hi=function(){this.nf()};_.k.Wh=function(){this.status=200;Bn(this,1)};var Bn=function(a,c){a.readyState=c;if(a.onreadystatechange)a.onreadystatechange()}; An.prototype.getAllResponseHeaders=function(){return"content-type: "+this.b.contentType};
var En=function(){_.O.call(this);this.f="closure_frame"+Cn++;this.j=[];Dn[this.f]=this},Fn;_.v(En,_.O);var Dn={},Cn=0,Gn=function(a,c){var d=_.Zf(a);_.vk(c,function(c,f){_.p(c)||(c=[c]);(0,_.Ha)(c,function(c){c=d.Ua("INPUT",{type:"hidden",name:f,value:c});a.appendChild(c)})})};_.k=En.prototype;_.k.Ca=null;_.k.Ha=null;_.k.uc=null;_.k.vi=0;_.k.Yb=!1;_.k.Qd=!1;_.k.Hd=null;_.k.tc=null;
_.k.send=function(a,c,d,e){if(this.Yb)throw Error("ca");a=new _.km(a);c=c?c.toUpperCase():"GET";d&&_.ym(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.Ea)()).toString(36));Fn||(Fn=_.Q("FORM"),Fn.acceptCharset="utf-8",d=Fn.style,d.position="absolute",d.visibility="hidden",d.top=d.left="-10px",d.width=d.height="10px",d.overflow="hidden",window.document.body.appendChild(Fn));this.Ca=Fn;"GET"==c&&Gn(this.Ca,a.b);e&&Gn(this.Ca,e);this.Ca.action=
a.toString();this.Ca.method=c;this.Yb=!0;this.uc=this.f+"_"+(this.vi++).toString(36);this.Ha=_.Zf(this.Ca).Ua("IFRAME",{name:this.uc,id:this.uc});_.y&&7>Number(_.vb)&&(this.Ha.src='javascript:""');e=this.Ha.style;e.visibility="hidden";e.width=e.height="10px";e.display="none";_.hb?e.marginTop=e.marginLeft="-10px":(e.position="absolute",e.top=e.left="-10px");if(_.y&&!_.wb("11")){this.Ca.target=this.uc||"";_.Zf(this.Ca).b.body.appendChild(this.Ha);_.N(this.Ha,"readystatechange",this.Fe,!1,this);try{this.b=
!1,this.Ca.submit()}catch(F){_.te(this.Ha,"readystatechange",this.Fe,!1,this),Hn(this)}}else{_.Zf(this.Ca).b.body.appendChild(this.Ha);e=this.uc+"_inner";d=_.Lj(this.Ha);window.document.baseURI?(a=_.Af(e),_.jd("Short HTML snippet, input escaped, safe URL, for performance"),a='<head><base href="'+_.Af(window.document.baseURI)+'"></head><body><iframe id="'+a+'" name="'+a+'"></iframe>',a=_.Ad(a,null)):(a=_.Af(e),_.jd("Short HTML snippet, input escaped, for performance"),a=_.Ad('<body><iframe id="'+a+
'" name="'+a+'"></iframe>',null));_.db&&!_.hb?_.xg(d.documentElement,a):d.write(_.wg(a));_.N(d.getElementById(e),"load",this.Kd,!1,this);var f=_.Fd("TEXTAREA",this.Ca);a=0;for(c=f.length;a<c;a++){var g=f[a].value,h=[];_.Ih(f[a],h,!1);h.join("")!=g&&(_.Wf(f[a],g),f[a].value=g)}f=d.importNode(this.Ca,!0);f.target=e;f.action=this.Ca.action;d.body.appendChild(f);g=_.Fd("SELECT",this.Ca);h=_.Fd("SELECT",f);a=0;for(c=g.length;a<c;a++)for(var m=_.Fd("OPTION",g[a]),q=_.Fd("OPTION",h[a]),t=0,w=m.length;t<
w;t++)q[t].selected=m[t].selected;g=_.Fd("INPUT",this.Ca);h=_.Fd("INPUT",f);a=0;for(c=g.length;a<c;a++)if("file"==g[a].type&&g[a].value!=h[a].value){this.Ca.target=e;f=this.Ca;break}try{this.b=!1,f.submit(),d.close(),_.gb&&_.rf(this.w,250,this)}catch(F){_.te(d.getElementById(e),"load",this.Kd,!1,this),d.close(),Hn(this)}}In(this)};
_.k.abort=function(){if(this.Yb){var a=Jn(this);if(a)if(_.be(a))a.Md(void 0);else if(a=_.oe(a)){var c=0,d;for(d in a.b)for(var e=a.b[d].concat(),f=0;f<e.length;++f)_.ue(e[f])&&++c}this.Qd=this.Yb=!1;this.dispatchEvent("abort");Kn(this)}};_.k.O=function(){this.Yb&&this.abort();En.J.O.call(this);this.Ha&&Ln(this);In(this);delete this.A;this.Hd=this.Ca=null;delete Dn[this.f]};_.k.$c=function(){return this.Qd};_.k.kf=function(){return this.Hd};_.k.le=function(){return _.Ck(this.Hd)};
_.k.Fe=function(){if("complete"==this.Ha.readyState){_.te(this.Ha,"readystatechange",this.Fe,!1,this);try{var a=_.Lj(this.Ha);if(_.y&&"about:blank"==a.location&&!window.navigator.onLine){Hn(this);return}}catch(c){Hn(this);return}Mn(this,a)}};_.k.Kd=function(){if(!_.db||_.hb||"about:blank"!=(this.Ha?_.Lj(Jn(this)):null).location){_.te(Jn(this),"load",this.Kd,!1,this);try{Mn(this,this.Ha?_.Lj(Jn(this)):null)}catch(a){Hn(this)}}};
var Mn=function(a,c){a.Yb=!1;try{var d=c.body;a.Hd=d.textContent||d.innerText}catch(f){var e=1}e||"function"!=typeof a.A||(c=a.A(c))&&(e=4);e?Hn(a):(a.Qd=!0,a.dispatchEvent("complete"),a.dispatchEvent("success"),Kn(a))},Hn=function(a){a.b||(a.Qd=!1,a.Yb=!1,a.dispatchEvent("complete"),a.dispatchEvent("error"),Kn(a),a.b=!0)},Kn=function(a){Ln(a);In(a);a.Ca=null;a.dispatchEvent("ready")},Ln=function(a){var c=a.Ha;c&&(c.onreadystatechange=null,c.onload=null,c.onerror=null,a.j.push(c));a.tc&&(_.l.clearTimeout(a.tc),
a.tc=null);_.gb||_.db&&!_.hb?a.tc=_.rf(a.o,2E3,a):a.o();a.Ha=null;a.uc=null};En.prototype.o=function(){this.tc&&(_.l.clearTimeout(this.tc),this.tc=null);for(;0!=this.j.length;){var a=this.j.pop();_.Id(a)}};var In=function(a){a.Ca&&a.Ca==Fn&&_.Uf(a.Ca)},Jn=function(a){return a.Ha?_.y&&!_.wb("11")?a.Ha:_.Lj(a.Ha).getElementById(a.uc+"_inner"):null}; En.prototype.w=function(){if(this.Yb){var a=this.Ha?_.Lj(Jn(this)):null;a&&!_.Xd(a,"documentUri")?(_.te(Jn(this),"load",this.Kd,!1,this),Hn(this)):_.rf(this.w,250,this)}};
var Nn=function(a,c,d){this.groupId=a;this.w="dp_"+a;this.B="count_"+a;this.o=c;this.b=!!d},On=/google(?:.[a-z]{2,3}){1,2}$/i,Pn=function(){var a=_.l.location.hostname.match(On);return a&&a[0]?a[0]:null};Nn.prototype.Pd=function(){return!!window.navigator.cookieEnabled};Nn.prototype.Ra=function(a){this.Pd()&&this.Dc(!1,a)};Nn.prototype.accept=function(a){this.Pd()&&this.Dc(!0,a)};Nn.prototype.Dc=function(){throw Error("da");};var Qn=function(a){0<a.o&&a.Pd()&&a.Yc(void 0,void 0)}; Nn.prototype.Yc=function(){throw Error("da");};var Rn=function(a){var c;(c=a.we())||(c=0<a.o&&a.xc()>=a.o);return c};Nn.prototype.xc=function(){return 0};Nn.prototype.we=function(){return!1};
var Sn=function(a,c,d,e,f){Nn.call(this,c,d);this.f=f;this.j=!e||-2==e||31536E3<e?31536E3:e;this.A=new RegExp("\\b"+this.groupId+"-([0-9]+):")};_.v(Sn,Nn);_.k=Sn.prototype;_.k.Pd=function(){window.navigator.cookieEnabled||(this.j=-1);return!0};_.k.Dc=function(a,c){var d=_.zj.get("OGP",""),e="-"+this.groupId+":";(new RegExp(e)).test(d)||(d+=e);(e=Pn())&&_.zj.set("OGP",d,this.j,"/",e);this.f&&this.f.Dc(a,c)};
_.k.Yc=function(a){var c=_.zj.get("OGPC",""),d=this.xc(c),e=!0;-1==d&&(e=!1,d=0);a=this.groupId+"-"+(d+(a||1))+":";c=e?c.replace(this.A,a):(c?c:"")+a;(e=Pn())&&_.zj.set("OGPC",c,this.j,"/",e);this.f&&this.f.Yc()};_.k.xc=function(a){var c=a||_.zj.get("OGPC","");a=-1;c&&(c=c.match(this.A))&&1<c.length&&(a=(0,window.parseInt)(c[1],10)||0);return a};_.k.we=function(){return-1!=_.zj.get("OGP","").indexOf("-"+this.groupId+":")};
var Tn=window.location.protocol+"//www.google.com/_/og/promos/",Un=function(a,c,d,e,f,g,h){var m={};m.p=d;m.g=c;m.a=e;m.at=f;m.eid=g;m.pid=1;if(h)m.t=h;else return a.log(Error("ea")),null;return m},Vn=function(a,c,d){if(a){var e=[Tn,d?"g":"z"];d&&c&&e.push(["?authuser=",c].join(""));c=e.join("");try{_.Fj=new zn;d=[];for(var f in a)a.hasOwnProperty(f)&&d.push(f+"="+a[f]);_.Lk(c,null,"POST",d.join("&"),null,void 0,!0)}catch(g){f=new En,_.N(f,"ready",f.ha,!1,f),f.send(c,"POST",!1,a)}}};
var Wn=function(a,c,d,e,f,g,h,m){Nn.call(this,c,d);this.f=a;h||m?(this.A=e,this.C=f,this.j=h||m||"",this.D=!!m,this.G=g):a.log(Error("fa"))};_.v(Wn,Nn);Wn.prototype.Dc=function(a,c){a?(a=this.C,(c=Un(this.f,this.groupId,this.A,"a",3,c||"",this.j))&&(c.u=a)):(a=this.C,(c=Un(this.f,this.groupId,this.A,"d",2,c||"",this.j))&&(c.u=a));Vn(c,this.G,this.D)};Wn.prototype.Yc=function(a,c){a=a||1;(c=Un(this.f,this.groupId,this.A,"i",1,c||"",this.j))&&(c.c=a);Vn(c,this.G,this.D)};
var Xn=function(a,c,d,e,f){Nn.call(this,c,d,f);this.j=a;this.f=e};_.v(Xn,Nn);Xn.prototype.Dc=function(){this.j.ld(this.f,this.w,"1",this.b)};Xn.prototype.Yc=function(a){a=this.xc()+(a||1);this.j.ld(this.f,this.B,a.toString(),this.b)};Xn.prototype.we=function(){return!!this.j.zd(this.f,this.w,this.b)};Xn.prototype.xc=function(){var a=this.j.zd(this.f,this.B,this.b);return(0,window.parseInt)(a||0,10)};
var Yn=function(a,c,d,e,f,g,h,m,q,t,w){if(t||w)try{var F=new Wn(a,f,g,h,m,d,t,w)}catch(qa){F=null}else F=null;switch(e){case 2:case 6:return F;case 1:return new Xn(c,f,g,q,void 0);default:return new Sn(a,f,g,m)}};var Zn=function(a,c,d,e,f,g,h,m){this.data={};_.Va(this.data,{ogsr:Math.round(1/a),ei:c,ct:e,cad:f,id:d,loc:window.google?window.google.sn:"",prid:g,ogd:h,ogprm:"up"});if(m)for(a=m.split("&"),c=0;c<a.length;c++)d=a[c].split("="),2==d.length&&(this.data[d[0]]=d[1])};_.v(Zn,_.$b);
var $n=function(a,c,d,e,f,g,h){_.G.call(this);this.b=a;this.w=c;this.j=d;this.B=e;this.A=f;this.o=g;this.f=h;_.u("gbar.up.sl",(0,_.r)(this.log,this))};_.v($n,_.G);$n.prototype.log=function(a,c,d,e,f){try{var g=this.w;if(void 0!=f&&null!=f)if(0<=f&&1>=f)g=f;else{this.b.log(Error("ga`"+c+"`"+d+"`"+f));return}if(Math.random()<=g){var h=new Zn(g,this.j,a,c,d,this.A,this.B,e);this.f?h.b():_.Wb(h)}}catch(m){this.b.log(Error("ga`"+c+"`"+d+"`"+f))}};
var ao=function(a){_.G.call(this);this.b=a;_.u("gbar.up.spd",(0,_.r)(this.ld,this));_.u("gbar.up.gpd",(0,_.r)(this.zd,this));_.u("gbar.up.dpc",(0,_.r)(this.si,this));_.u("gbar.up.iic",(0,_.r)(this.ni,this));_.u("gbar.up.gcc",(0,_.r)(this.Ug,this))};_.v(ao,_.G);var bo=function(){try{return!!_.l.localStorage&&"object"==typeof _.l.localStorage}catch(a){return!1}},co=function(a){return a&&a.style&&a.style.behavior&&"undefined"!=typeof a.load};_.k=ao.prototype;
_.k.ld=function(a,c,d,e){try{window.navigator.cookieEnabled&&(e||(c="og-up-"+c),bo()?_.l.localStorage.setItem(c,d):co(a)&&(a.setAttribute(c,d),a.save(a.id)))}catch(f){f.code!=window.DOMException.QUOTA_EXCEEDED_ERR&&this.b.log(f)}};_.k.zd=function(a,c,d){try{if(!window.navigator.cookieEnabled)return"";d||(c="og-up-"+c);if(bo())return _.l.localStorage.getItem(c);if(co(a))return a.load(a.id),a.getAttribute(c)}catch(e){e.code!=window.DOMException.QUOTA_EXCEEDED_ERR&&this.b.log(e)}return""}; _.k.si=function(a,c){(new Sn(this.b,a,1,c)).Ra()};_.k.ni=function(a,c){Qn(new Sn(this.b,a,1,c))};_.k.Ug=function(a,c){return(new Sn(this.b,a,1)).xc(c)};
var fo=function(a,c,d,e,f,g){_.lh.call(this,a,e);this.f=a;this.w=_.I(_.B(c,1));this.Na=_.I(_.B(c,2));this.V=_.I(_.B(c,3));_.C(c,4,25);this.Ia=_.J(_.B(c,5));this.Kb=_.J(_.C(c,6,-1));this.$=_.H(_.B(c,9));this.W={sk:"i",accept:"a",Ra:"d",nd:"x"};this.B=eo;this.ab=!1;this.H=f;this.Cb=g;this.M=_.P(this.B.Wf,this.f);this.nd=_.P(this.B.jg,this.f);this.X=_.P(this.B.$f,this.f);this.Bb="";this.hb=!1;var h,m;c.C&&(h=_.I(c.C()));c.B&&(m=_.I(c.B()));if(m||h)this.Bb=m||h||"",this.hb=!!m;this.o=Yn(e,this.Cb,d,this.Ia,
this.Na,_.J(_.C(c,4,25)),this.w,this.Kb,this.f,h,m)};_.v(fo,_.lh);fo.prototype.O=function(){fo.J.O.call(this);this.X=this.nd=this.M=null};var eo={Wf:"gb_gd",jg:"gb_xd",$f:"gb_yd",od:"gb_g"};fo.prototype.C=function(){_.S(this.f,this.B.od)||(_.T(this.f,this.B.od),this.f.removeAttribute("aria-hidden"))};fo.prototype.close=function(){_.S(this.f,this.B.od)&&(_.U(this.f,this.B.od),this.f.setAttribute("aria-hidden","true"))};var go=function(a,c,d){var e=_.Sg;c&&_.Em(a,c,e,d,!1,a)};
fo.prototype.rd=function(){go(this,this.M,this.Bd);go(this,this.nd,this.Nb);go(this,this.X,this.Mb)};fo.prototype.G=function(){return""};var ho=function(a){var c="";a&&(a=a.getAttributeNode("data-ved"))&&a.value&&(c=["&ved=",a.value].join(""));return c},io=function(a){var c=a.G();a.$&&(c+="&vis=0");a.H.log(a.w,a.V,"i",c,1)};fo.prototype.Ja=function(){this.$||Rn(this.o)?this.$&&!Rn(this.o)&&io(this):(this.rd(),this.C(),Qn(this.o),io(this))};
var jo=function(a,c,d,e,f,g){var h=c==a.W.accept;a.ab||(h&&!g||a.H.log(a.w,a.V,c,a.G()+ho(d),1),f||0==a.Ia?2==a.Ia&&(c=a.H,d=a.hb,e=Un(c.b,a.Na,a.w,"l",3,e,a.Bb),Vn(e,c.o,d)):(h?a.o.accept(e):a.o.Ra(e),a.ab=!0));a.close()};fo.prototype.Bd=function(a,c,d){jo(this,this.W.accept,a.target,"2",c,d)};fo.prototype.Nb=function(a,c){jo(this,this.W.nd,a.target,"1",c)};fo.prototype.Mb=function(a,c){jo(this,this.W.Ra,a.target,"3",c)};
var ko=function(a,c){this.f=c;this.b={};this.b.mouseout=_.I(_.B(a,1));this.b.mouseover=_.I(_.B(a,2));this.b.mousedown=_.I(_.B(a,3))},lo=function(a,c){if(c)for(var d in a.b){var e=a.b[d];e&&_.ih(a.f,c,d,(0,_.r)(function(a){c.style.color=a},a,e))}},mo=function(a,c){for(var d=0;d<c.length;d++)lo(a,c[d])};
var po=function(a,c,d,e,f){_.Jm.call(this,a,"pc",e,f,!0);f=_.E(c,un,1)||new un;this.Pb=d;this.N=_.I(_.B(f,1));this.Ab=_.I(_.B(f,3));this.hb=_.I(_.B(f,2));this.Ud=_.I(f.B());this.Bb=_.J(_.B(c,6));this.Lb=_.J(_.C(f,4,25),25);this.Z=!_.H(_.B(f,9));_.B(c,9);_.B(f,10);this.S=_.P("gb_gd",this.f);this.Nb=_.H(_.B(c,17),!1);this.Ob=_.H(_.B(c,10));this.Mb=_.H(_.B(c,14));this.H=this.Ob||this.Mb;this.ua=_.P("gb_Tf");this.Sb=_.P("gb_Uf");this.Qb=_.P("gb_Rf");this.Rb=_.P("gb_Sf");this.Na=_.I(_.B(c,12));this.w=
_.P("gb_Qf");this.V=_.P("gb_ud");this.T=window.document.getElementById("gb");var g=_.fc.ra();this.yb=_.jc(g,"p_log");this.ab=_.jc(g,"p_st");this.Kb=_.J(_.B(f,5));this.W=Yn(e,this.ab,d,this.Kb,this.hb,this.Lb,this.N,this.Bb,this.f,_.I(f.C()),_.I(f.B()));this.T&&(this.X=_.P("gb_ib",this.T));this.D=!1;if(this.X&&!Rn(this.W)&&!this.D){d=_.I(_.B(c,2));if("n"!=d&&(this.L=(e=no[d])?_.P(e,this.X):null,!this.L)){this.A.log(Error("ha"),{target:d});return}this.ka="gb_od";"b"==_.B(c,3)&&(_.T(this.f,"gb_9c"),
this.ka="gb_pd");oo(this);d=_.E(c,vn,4)||new vn;mo(new ko(d,this.A),[this.S]);this.yb.log(this.N,this.Ab,"i","&vis="+(this.Z?"1":"0"),this.H?1:void 0);d=this.ab;e=this.N;_.B(c,7)&&d.ld(a,"OGPL",e);this.Va=0;this.Z?this.vb():this.G&&this.B.log(this.G,_.Nm(this));Qn(this.W)}this.rb()};_.v(po,_.Jm);var no={p:"gb_eb",s:"gb_Lf",i:"gb_xg",v:"gb_8"};po.prototype.O=function(){po.J.O.call(this);this.T=this.X=this.L=this.button=this.Aa=null};po.prototype.vd=function(){};
var qo=function(a){var c=_.P("gb_nd",a.f);if(c)return c;c=_.Hd("IFRAME");c.frameBorder="0";c.tabIndex=-1;_.T(c,"gb_nd");var d=_.Jj(_.jd("javascript:''"));c.src=_.pd(d);a.T.appendChild(c);return c};po.prototype.vb=function(){po.J.vb.call(this);var a=qo(this);if(a){var c=_.P("gb_aa",this.f);c.appendChild(a);a=a.style;a.width=c.offsetWidth+"px";a.height=c.offsetHeight+"px";a.visibility="visible";a.top="-1px";a.left="-1px"}this.Va=this.b.offsetWidth;ro(this,!this.H&&!this.Nb)};
po.prototype.close=function(){if(po.J.close.call(this)){var a=qo(this);a&&(a=a.style,a.width="",a.height="",a.visibility="",a.top="",a.left="");ro(this,!1);return!0}return!1};var ro=function(a,c){a.L&&(c?_.T(a.L,a.ka):_.U(a.L,a.ka))};po.prototype.uf=function(){};po.prototype.Cd=function(){};
var oo=function(a){a.Aa=_.P("gb_ad",a.f);a.Aa&&_.Em(a,a.Aa,_.Sg,a.ki,!0,a);a.Ja=_.P("gb_yd",a.f);a.Ja&&_.Em(a,a.Ja,_.Sg,a.Ah,!0,a);a.S&&_.Em(a,a.S,_.Sg,a.qh,!0,a);for(var c=_.zh("gb_b",a.X),d=0;d<c.length;d++)_.Em(a,c[d],_.Sg,a.Ni,!0,a);c=_.Rh();a.j(c,"resize",a.Oi,!1,a);a.w&&(a.j(a.w,"focus",a.jc,!1,a),a.j(a.w,"blur",a.hc,!1,a),a.j(a.w,"keyup",function(a){13==a.keyCode&&(a.preventDefault(),this.S.click())},!1,a),a.w.pattern="^\\+?1?[-()\\s]*([\\d][-()\\s]*){0,10}")};
po.prototype.jc=function(){this.V&&_.T(this.V,"gb_vd")};po.prototype.hc=function(){this.V&&_.U(this.V,"gb_vd")};var so=function(a,c){a.D||(a.W.Ra(),("a"!=c||a.H)&&a.yb.log(a.N,a.Ab,c,void 0,1),a.close(),a.D=!0)};_.k=po.prototype;_.k.Oi=function(){try{if(this.b&&this.Z){var a=276,c=window.document.getElementById("hplogo");c&&(a=Math.max(a,c.offsetWidth));2*(this.Va+((0,window.parseInt)(this.b.style.right,10)||0))+a>window.document.body.clientWidth?this.close():!Rn(this.W)&&!this.D&&this.vb()}}catch(d){this.A.log(d)}};
_.k.Ni=function(){this.H?(this.D=!0,this.close()):so(this,"a")};_.k.ki=function(){so(this,"x")};_.k.Ah=function(){so(this,"n")};_.k.qh=function(a){this.w&&11!=to(this.w.value).length?(this.w.pattern&&(this.w.pattern="^\\+?1?[-()\\s]*([0,2-9][-()\\s]*)([\\d][-()\\s]*){9}$",this.w.dispatchEvent(new window.Event("input"))),a.preventDefault(),a.stopPropagation()):(so(this,"a"),this.H&&(a.preventDefault(),a.stopPropagation(),uo(this)))};
var uo=function(a){if(a.w&&11!=to(a.w.value).length)a.va();else{vo(a,a.ua);var c=(0,_.r)(a.bc,a),d=(0,_.r)(a.va,a);_.Fj=new zn;_.Lk("//www.google.com/_/og/promos/g?authuser="+a.Pb,function(){this.$c()?c(this.le()):d()},"POST",wo(a),null,void 0,!0)}},wo=function(a){var c="d2m=igs&g="+a.hb+"&p="+a.N+"&t="+a.Ud;a.w&&(c+="&pn="+to(a.w.value));a.Na&&(c+="&s="+a.Na);return c},vo=function(a,c,d){_.U(c,"gb_6a");d&&0<d&&(0,window.setTimeout)((0,_.r)(a.ya,a,c),d)};
po.prototype.ya=function(a){_.V(a,"gb_6a",!0)};po.prototype.bc=function(a){var c=new yn(a.PromoAsyncResponse);a=_.B(c,1);c=_.B(c,2);a&&c&&0!=c.length?(_.Wf(this.Rb," "+c+" "),this.ya(this.ua),vo(this,this.Sb,15E3)):this.va()};po.prototype.va=function(){this.ya(this.ua);vo(this,this.Qb,15E3)};var to=function(a){a=a.replace(/[^0-9]/g,"");a.startsWith("1")||(a="1"+a);return a};
var yo=function(a,c,d,e,f,g){var h=_.E(c,un,1)||new un;fo.call(this,a,h,d,e,f,g);this.Sb=d;this.Y=_.I(_.B(c,12));d=_.I(h.B());this.Lb="d2m=igs&g="+this.Na+"&p="+this.w+"&t="+d;this.ka=!_.H(_.B(h,9));this.Qb=_.H(_.B(c,17),!1);this.Rb=_.H(_.B(c,10));this.Pb=_.H(_.B(c,14));this.Ob=_.H(_.B(c,16));this.L=this.Rb||this.Pb;this.yb=_.H(_.B(c,13));this.va=_.P("gb_Tf");this.jc=_.P("gb_Uf");this.bc=_.P("gb_Rf");this.hc=_.P("gb_Sf");this.b=_.P("gb_Qf");this.R=_.P("gb_ud");this.D=_.P("gb_aa",this.f);this.Ab=0;
if(this.D||this.L||this.yb){if(this.N=window.document.getElementById("gb"))this.T=_.P("gb_ib",this.N);this.Z=!1;this.Va=!0;this.T&&!Rn(this.o)&&(h=_.I(_.B(c,2)),d=null,"n"!=h&&((d=(d=xo[h])?_.P(d,this.T):null)||this.A.log(Error("ha"),{target:h})),this.S=d,this.ua="gb_od","b"==_.B(c,3)&&(_.T(this.f,"gb_9c"),this.ua="gb_pd"),h=_.E(c,vn,4)||new vn,mo(new ko(h,this.A),[this.M]),h="&vis="+(this.ka?"1":"0"),this.H.log(this.w,this.V,"i",this.G()+h,this.L||this.Y?1:void 0),h=this.Cb,d=this.w,_.B(c,7)&&h.ld(a,
"OGPL",d),this.Ja())}else this.A.log(Error("ia"))};_.v(yo,fo);var xo={p:"gb_eb",s:"gb_Lf",i:"gb_xg",v:"gb_8"};yo.prototype.O=function(){yo.J.O.call(this);this.D=this.N=this.T=this.S=this.button=null};yo.prototype.G=function(){return"cot=2"};var zo=function(a){var c=_.P("gb_nd",a.f);if(c)return c;c=_.Hd("IFRAME");c.frameBorder="0";c.tabIndex=-1;_.T(c,"gb_nd");var d=_.Jj(_.jd("javascript:''"));c.src=_.pd(d);a.N.appendChild(c);return c};
yo.prototype.C=function(){yo.J.C.call(this);var a=zo(this),c=this.D?this.D:this.f;a&&(c.appendChild(a),a=a.style,a.width=c.offsetWidth+"px",a.height=c.offsetHeight+"px",a.visibility="visible",a.top="-1px",a.left="-1px");this.Ab=c.offsetWidth;Ao(this,!this.L&&!this.Qb);this.b&&(this.b.pattern="^\\+?1?[-()\\s]*([\\d][-()\\s]*){0,10}")};yo.prototype.close=function(){yo.J.close.call(this);var a=zo(this);a&&(a=a.style,a.width="",a.height="",a.visibility="",a.top="",a.left="");Ao(this,!1)};
var Ao=function(a,c){a.S&&(c?_.T(a.S,a.ua):_.U(a.S,a.ua))};_.k=yo.prototype;_.k.rd=function(){yo.J.rd.call(this);for(var a=_.zh("gb_b",this.T),c=0;c<a.length;c++)go(this,a[c],this.Ji);this.yb||(a=_.Rh(),this.j(a,"resize",this.Ki,!1,this));this.b&&(this.j(this.b,"focus",this.Mi,!1,this),this.j(this.b,"blur",this.Li,!1,this),this.j(this.b,"keyup",function(a){13==a.keyCode&&(a.preventDefault(),this.M.click())},!1,this))};_.k.Mi=function(){this.R&&_.T(this.R,"gb_vd")};
_.k.Li=function(){this.R&&_.U(this.R,"gb_vd")};_.k.Ki=function(){try{if(this.D&&this.ka){var a=276,c=window.document.getElementById("hplogo");c&&(a=Math.max(a,c.offsetWidth));2*(this.Ab+((0,window.parseInt)(this.D.style.right,10)||0))+a>window.document.body.clientWidth?(this.close(),this.Z=!0):this.Va&&this.Z&&!Rn(this.o)&&(this.C(),this.Z=!1)}}catch(d){this.A.log(d)}};_.k.Ji=function(a){this.L?(this.Va=!1,this.close()):jo(this,"a",a.target,"2")};
_.k.Bd=function(a,c){this.Ob&&null!=window.launchConsentDialog?(a.preventDefault(),a.stopPropagation(),this.close(),window.launchConsentDialog()):this.b&&11!=Bo(this.b.value).length?(this.b.pattern&&(this.b.pattern="^\\+?1?[-()\\s]*([0,2-9][-()\\s]*)([\\d][-()\\s]*){9}$",this.b.dispatchEvent(new window.Event("input"))),a.preventDefault(),a.stopPropagation()):(jo(this,"a",a.target,"2",c),this.L&&(a.preventDefault(),a.stopPropagation(),this.H.log(this.w,this.V,"a",this.G(),1),Co(this)))};
var Co=function(a){if(a.b&&11!=Bo(a.b.value).length)a.ya();else{Do(a,a.va);var c=(0,_.r)(a.Qc,a),d=(0,_.r)(a.ya,a);_.Fj=new zn;_.Lk("//www.google.com/_/og/promos/g?authuser="+a.Sb,function(){this.$c()?c(this.le()):d()},"POST",Eo(a),null,void 0,!0)}},Eo=function(a){var c=a.Lb;a.b&&(c+="&pn="+Bo(a.b.value));a.Y&&(c+="&s="+a.Y);return c},Do=function(a,c,d){_.U(c,"gb_6a");d&&0<d&&(0,window.setTimeout)((0,_.r)(a.Aa,a,c),d)};yo.prototype.Aa=function(a){_.V(a,"gb_6a",!0)};
yo.prototype.Qc=function(a){var c=new yn(a.PromoAsyncResponse);a=_.B(c,1);c=_.B(c,2);a&&c&&0!=c.length?(_.Wf(this.hc," "+c+" "),this.Aa(this.va),Do(this,this.jc,15E3)):this.ya()};yo.prototype.ya=function(){this.Aa(this.va);Do(this,this.bc,15E3)};yo.prototype.Ja=function(){this.ka&&(this.rd(),this.C(),Qn(this.o))};var Bo=function(a){a=a.replace(/[^0-9]/g,"");a.startsWith("1")||(a="1"+a);return a};
var Go=function(a,c,d,e,f,g,h){fo.call(this,a,c,e,f,g,h);this.b=[];d&&mo(new ko(d,f),[this.M,this.nd,this.X]);Fo(this)};_.v(Go,fo);var Fo=function(a){_.ih(a.A,a.f,"mouseover",function(a){a.stopPropagation()})};Go.prototype.G=function(){return"ic="+this.o.xc()};Go.prototype.C=function(){Go.J.C.call(this);for(var a=0;a<this.b.length;a++)this.b[a]("o")};Go.prototype.close=function(){Go.J.close.call(this);for(var a=0;a<this.b.length;a++)this.b[a]("c")};
var Ho={consent:function(){return window.launchConsentDialog}},Io=function(a){return _.Td(a,"js:")?null!=Ho[a.slice(3)]:!1};var Jo=function(a,c,d,e,f,g){Go.call(this,a,_.E(c,un,1),_.E(c,vn,3),d,e,f,g);this.L=_.H(_.C(c,5,!1));this.D=_.I(_.B(c,2));this.N=_.H(_.C(c,4,!1))};_.v(Jo,Go);
Jo.prototype.Bd=function(a){Jo.J.Bd.call(this,a,this.L,_.n(this.D)?Io(this.D):!1);a=this.A;var c=this.D,d=this.N;c&&("function"==typeof c?c.call():"string"==typeof c&&(_.Td(c,"js:")?(c=c.slice(3),d=Ho[c],!d&&a?a.log(Error("ja`"+c)):(d=d(),!d&&a?a.log(Error("ka`"+c)):d())):d?(a=_.Nd(c),_.l.open(_.Jd(a))):null!=_.l.location&&_.Od(_.l.location,c)))}; var Ko=function(a,c,d,e,f,g){var h=_.P("gb_Vc"),m=_.E(a,xn,5);m&&h&&(d.fe("up","up",["2","9","6"]),d.register("up",function(d){d&&(d=_.J(_.B(a,8)),d=new Jo(h,m,d,c,f,e),d.b.push(g),d.Ja())}))};
var Lo=function(){_.G.call(this)};_.v(Lo,_.G);var Mo=function(){_.G.call(this)};_.v(Mo,_.G);var No=function(a,c){_.G.call(this);this.o=c;this.f={};this.w={};this.b=null;this.j=1;this.A=!1;this.B=a;_.u("gbar.up.r",(0,_.r)(this.register,this));_.u("gbar.up.nap",(0,_.r)(this.fe,this));_.u("gbar.up.aop",(0,_.r)(this.ng,this));_.u("gbar.up.tp",(0,_.r)(this.Gf,this));_.u("gbar.up.ssp",(0,_.r)(this.Le,this))};_.v(No,_.G);var Oo=function(a,c,d){return-1==(0,_.Ga)(c,a.j)?(a.o.log(Error("la`"+a.j+"`"+d)),!1):!0};_.k=No.prototype;
_.k.register=function(a,c){Oo(this,[1,2],"r")&&(this.f[a]=this.f[a]||[],this.f[a].push(c),2==this.j&&_.l.setTimeout((0,_.r)(function(){c(this.Le(a))},this),0))};_.k.fe=function(a,c,d){if(Oo(this,[1],"nap")&&d){for(var e=0;e<d.length;e++)this.w[d[e]]=!0;this.B.log(a,c,"nap","tpt="+d.join(","))}};_.k.ng=function(a,c,d){if(Oo(this,[1],"aop")&&d){if(this.b)for(var e in this.b)this.b[e]=this.b[e]&&-1!=(0,_.Ga)(d,e);else for(this.b={},e=0;e<d.length;e++)this.b[d[e]]=!0;this.B.log(a,c,"aop","tpt="+d.join(","))}};
_.k.Gf=function(){try{if(this.j=2,!this.A){this.A=!0;for(var a in this.f)for(var c=this.f[a],d=0;d<c.length;d++)try{var e=c[d],f=this.Le(a);e.apply(null,[f])}catch(g){this.o.log(g)}}}catch(g){this.o.log(g)}};_.k.Le=function(a){if(Oo(this,[2],"ssp")){var c=!this.w[a];this.b&&(c=c&&!!this.b[a]);return c}return!1};
_.on.log(1);var Po=_.P("gb_kc");if(Po){var Qo=_.P("gb_8b",Po);Qo&&new _.mh(Qo,_.L,_.Bc)};var Yo=function(){var a=Ro,c=So,d=To,e=Uo,f=Vo,g=Wo;this.o=Xo;this.f=a;this.j=g;this.b=c;this.w=d;this.A=e;this.G=_.Bc;this.B=f},Zo;Yo.prototype.C=function(){var a=_.E(this.j,wn,4),c=a&&_.B(a,13)?_.P("gb_Zc"):_.P("gb_8c"),d=_.P("gb_Pf");if(a&&c&&d){var e=this.j,f=this.f,g=this.A,h=this.G,m=this.w,q=this.o;this.b.register("7",function(t){t&&(_.Vi(q,d),t=_.J(_.B(e,8)),_.B(a,8)?new yo(c,a,t,f,g,m):new po(c,a,t,f,h))});this.b.fe("7","7",["5"])}}; Yo.prototype.D=function(){var a=this.o;Ko(this.j,this.f,this.b,this.w,this.A,function(){_.Oi(a)})};
var Wo=_.E(_.vc,tn,15),$o=_.xc();
if(Wo&&_.Y){var ap=_.E(Wo,wn,4),bp;(bp=!ap)||(bp=!_.B(ap,15));if(bp){var cp=_.I(_.B(_.wc(),10)),dp=_.fc.ra(),ep=_.L,fp=_.J(_.B(Wo,8)),gp;gp=+_.C(Wo,1,1E-4);var hp=_.J(gp,1E-4),ip;ip=_.B(Wo,2);var jp=_.I(ip),kp;kp=_.B(Wo,3);var lp=new $n(ep,hp,cp,jp,_.I(kp),fp,!1),mp=new ao(ep);_.hc("p_log",lp);_.hc("p_st",mp);_.hc("p_tr",new No(lp,ep));_.hc("p_mgmhp",new Mo(ep,mp));_.hc("p_dse",new Lo(ep));var So=_.jc(dp,"p_tr"),To=_.jc(dp,"p_st"),Uo=_.jc(dp,"p_log"),Vo=_.Ud("api"),np;if(np=To.zd(void 0,"OGPL")){_.B($o,
1)&&Uo.log(np,"7","s",void 0,1);var op=To,pp="OGPL";try{window.navigator.cookieEnabled&&(pp="og-up-"+pp,bo()?_.l.localStorage.removeItem(pp):co(void 0)&&((void 0).removeAttribute(pp),(void 0).save((void 0).id)))}catch(a){a.code!=window.DOMException.QUOTA_EXCEEDED_ERR&&op.b.log(a)}}var qp,Xo=_.Y,Ro=_.L;Zo||(Zo=new Yo);qp=Zo;var rp={};rp.up=qp.D;rp["7"]=qp.C;for(var sp in rp)try{rp[sp].apply(qp)}catch(a){qp.f.log(Error(sp))}qp.B.td();qp.b.Gf()}};

}catch(e){_._DumpException(e)}
try{
var Ky=function(a){_.A(this,a,0,-1,null)};_.v(Ky,_.z);if(null!=_.E(_.vc,Ky,20)){var Ly;a:{try{if(window.document.domain==window.top.document.domain){var My=/google\.(com?\.)?[a-z]{2,3}$/.exec(window.document.domain);Ly=My&&My[0];break a}}catch(a){}Ly=null}var Ny=Ly;if(Ny){var Oy=new Date;_.zj.set("1P_JAR",[Oy.getUTCFullYear(),Oy.getUTCMonth()+1,Oy.getUTCDate(),Oy.getUTCHours()].join("-"),2592E3,"/",Ny)}}else _.L.log("Shuli configuration missing.");

}catch(e){_._DumpException(e)}
})(this.gbar_);
// Google Inc.
